version: "3"
services:
  app:
    build: "."
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "db"

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ".postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
