# Default values for traceochart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: gcr.io/zeroapi-268514/traceo

secretKeyBase: "12345678"

postgres:
  password: "12345678"
